### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by danibene** [brainhack-school2020/koudyk_bhs_project#1]
Hi Kendra,

Cool idea :) I was wondering - do you already know how you will evaluate the performance of the keyword extraction?

**Comment by koudyk** [comment]
That's a great question, thanks :) 
Ideally, I would manually annotate a subset of my dataset to train/test my method for extracting keyworks. But I've tried to pick a simple task (searching for 'python' and 'matlab') so that I won't have to spend a long time on the text-mining method and on manual annotation. I was hoping to focus on the packaging/testing aspect of the project, but if I made this into a larger-scale project, I'd definitely have to spend time on this problem!
