### ISSUE TITLE
Scope - abstract or full text

### ISSUE THREAD

**Issue by dnmacdon** [brainhack-school2020/koudyk_bhs_project#2]
Cool idea! Does your dataset give you access to the full text, or only the abstract? Would you limit your data mining to the abstract?

**Comment by koudyk** [comment]
Hi, thanks for the question, it's an important point to consider! I'll be using open-access articles, so I'll have the full text. This is important for my task because most people don't say things like whether they used Python or Matlab in their abstracts.

If you're interested in this issue, [NeuroSynth](https://neurosynth.org/) is an automated meta-analytic tool that uses only abstracts to determine what a paper is 'about', and [NeuroQuery](neuroquery.org/) is another that uses full texts.
